dotnet fixes

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -102,7 +102,8 @@ jobs:
           echo "Building .NET SDK..."
           cd packages/dotnet || (echo "Failed to cd to packages/dotnet" && exit 1)
           dotnet restore || (echo ".NET restore failed" && exit 1)
-          dotnet build -q || (echo ".NET build failed" && exit 1)
+          dotnet clean || (echo ".NET clean failed" && exit 1)
+          dotnet build --no-incremental -q || (echo ".NET build failed" && exit 1)
           cd ../.. || (echo "Failed to cd back from dotnet" && exit 1)
 
           echo "Building Rust SDK..."
